### ISSUE TITLE
Entfernung der Links aus der oberen Bildschirmecke

### ISSUE THREAD

**Issue by KirstenWesker** [findme-react/js-webapp#8]
Bitte Funktionalität in die Buttons etc. bekommen und keine Navigation über die behelfsmäßigen Links mehr.

**Comment by Akeshihiro** [comment]
Das war für Dummy-Zwecke für das Routing-Modul, denn da gabs noch keine Oberfläche, in der man etwaige Tests hätte machen können. Kann erst nach den Umbauarbeiten für einen verwertbaren Pull-Request angegangen werden, falls das nicht während der Umbauarbeiten schon verschwindet. Ich lasse das Issue daher erst einmal noch offen, kann aber sein, dass es obsolet werden könnte.
